{
  {
    damage: {
      "DAMAGE_FORM": "Damaged Card Form",
      "EMP_ID": "Employee Id",
      "EMP_TYPE": "Employee Type",
      "PERMANENT": "Permanent",
      "TEMPORARY": "Temporary",
      "NAME": "Employee Name",
      "DOJ": "Date Of Joining",
      "DESIGNATION": "Designation",
      "PROJECT": "Project/Function",
      "OU": "OU/Designation",
      "COMMENTS_HEADING": "**First Submit Your damaged Access Card then  request for a new card And you Will Have A New Card In Two Days",
      "SUBMIT_DATE": "Enter The Date Of Card submitted:";
      "SUBMIT": "Submit Your Request",
      "BACK": "Go Back"
    }

    locationchange: {
      "GENERAL": "General (All Fields Are Mandatory)",
      "CATEGORY": "Category",
      "ACCESS_TYPE": "Access type",
      "LOCATION_CHANGE_FORM": "Location Change Form",
      "EMP_ID": "Employee ID",
      "EMP_TYPE": "Employee Type",
      "PERMANANT": "Permanant",
      "TEMPORARY": "Temporary",
      "NAME": "Name",
      "DOJ": "Date of Joining",
      "DESIGNATION": "Designation",
      "PROJECT": "Project / Function",
      "OU": "OU / Department",
      "STATUS": "Status",
      "DOE": "Date of Expiry of Temporary Card",
      "PROJECT_TRANSFER": "Project Transfer (In Case of Transfer)",
      "EXISTING_LOCATION": "Existing Location",
      "NEW_LOCATION": "New Location",
      "SIGNATURES": "Signatures",
      "APPLICANTS_SIGNATURES": "Applicants Signature",
      "DATE": "Date",
      "SUBMIT": "Submit Your Request",
      "BACK": "Go Back"
    }

    lost: {
      "EMP_ID": "Employee Id",
      "EMP_TYPE": "Employee Type",
      "PERMANANT": "Permanant",
      "TEMPORARY": "Temporary",
      "NAME": "Name",
      "DOJ": "Date of Joining",
      "DESIGNATION": "Designation",
      "PROJECT": "Project / Function",
      "OU": "OU / Department",
      "SUBMIT": "Submit Your Request",
      "BACK": "Go Back"
    }

    thirdparty: {
      "GENERAL": "General (All Fields Are Mandatory)",
      "CATEGORY": "Category",
      "ACCESS_TYPE": "Access Type",
      "THIRD_PARTY": "Third Party Form",
      "EMP_ID": "Employee Id",
      "NAME": "Employee Name",
      "VISITOR_NAME": "Visitor Name",
      "DURATION": "Duration",
      "VISITING_PURPOSE": "Visiting Purpose",
      "SIGNATURES": "Signatures",
      "APPLICANTS_SIGNATURE": "Applicants Signature",
      "DATE": "Date",
      "SUBMIT": "Submit Your Request",
      "BACK": "Go Back"
    }

    newaccess: {
			"IR": "IR 71 Form",
      "EMPP_ID": "Employee ID",
      "EMPP_TYPE": "Employee Type",
      "TEMP": "Temporary",
      "PERM": "Permanent",
      "NAME": "NAME",
      "DATE_JOINING": "Date Of Joining",
      "DESG": "Designation",
      "PROJ": "Project / Function",
      "OU": "OU / Department",
      "STATUS": "Status",
      "DATE_EXP_CARD": "Date of Expiry of Temporary Card",
      "PRO_TRANS": "Project Transfer (In Case of Transfer",
      "EXIST_PROJ": "Existing Project Name",
      "NEW_PROJ": "New Project Name",
      "SIGN": "Signatures",
      "APPLICANT_SIGN": "Applicants Signature",
      "DATE": "Date",
      "SUBMIT": "Submit Your Request",
      "BACK": "Go Back",
      "MSG": "Message",
      "FORWARD_MSG": "Your request has been forwarded to Supervisor",
      "BACK_MSG": "Do you really want to go back?"
    }

    employeedash: {
      "PLUGIN_CSS": "Plugin Css",
      "CENTRALIZED_ACCESS_CONTROL": "Centralized Access Control",
      "DASHBOARD": "Dashboard",
      "MY_DASHBOARD": "My Dashboard",
      "YOUR_DETAILS": "Your Details",
      "SUPERVISOR_NAME": "Chander Sehgal",
      "SUP_NAME": "Supervisor Name",
      "LOCATION": "LOCATION",
      "LOC": "Location",
      "DEPT": "SSB-CSDM-RP",
      "OU": "OU",
      "UPDATES": "Updated yesterday at 11:59 PM",
      "COPYRIGHT": "Iniitiian.com 2017"
    }

    supervisorform: {
      "IR_HEADING": "IR 71 Access Request Form",
      "VERSION": "Ver 1.0",
      "GENERAL": "General (All Fields Are Mandatory)",
      "CATEGORY": "Category",
      "ACCESS_TYPE": "Access type",
      "IR": "IR 71 Form",
      "EMPP_ID": "Employee ID",
      "EMPP_TYPE": "Employee Type"
      "NAME": "NAME",
      "DATE_JOINING": "Date Of Joining",
      "DESG": "Designation",
      "PROJ": "Project / Function",
      "OU": "OU / Department",
      "STATUS": "Status",
      "DATE_EXP_CARD": "Date of Expiry of Temporary Card",
      "PRO_TRANS": "Project Transfer (In Case of Transfer",
      "EXIST_PROJ": "Existing Project Name",
      "NEW_PROJ": "New Project Name",
      "SIGN": "Signatures",
      "APPLICANT_SIGN": "Applicants Signature",
      "DATE": "Date",
      "PHYSICAL_ACCESS": "Physical Access Requirements (To be filled by DH/PH/PM)",
      "ZONES": "Zones",
      "PUBLIC": "Public",
      "INTERNAL": "Internal",
      "RESTRICTED": "Restricted",
      "DETAILS": "Details",
      "TEMP": "Temporary",
      "PERM": "Permanent",
      "Auth_SIGN": "Authorization Signatures (As Applicable)",
      "HRO": "HRO",
      "CSO": "CSO",
      "DH/PH/PM": "DH/PH/PM",
      "CISO": "CISO",
      "ACCEPT": "Accept",
      "SENDBACK": "Send Back",
      "MSG": "Message",
      "FORWARD_MSG": "Your request has been forwarded to Hr",
      "BACK_MSG": "Do you really want to send it back to Employee?"
    }

    supervisordash: {

    }

    hrform: {
      "IRHEADING": "IR 71 Access Request Form",
      "VERSION": "Ver 1.0",
      "GUIDELINES": "Click Here To See Guidelines",
      "GENERAL": "General (All Fields Are Mandatory)",
      "CATEGORY": "Category",
      "ACCESS": "Access type",
      "IR_FORM": "IR 71 Form",
      "EMP_ID": "Employee ID",
      "EMP_TYPE": "Employee Type",
      "NAME": "Name",
      "DOJ": "Date of Joining",
      "DESIGNATION": "Designation",
      "PROJECT": "Project / Function",
      "OU": "OU / Department",
      "STATUS": "Status",
      "PERMANENT": "Permanant",
      "TEMPORARY": "Temporary",
      "DOE_TEMP": "Date of Expiry of Temporary Card",
      "PROJECT_TRANSFER": "Project Transfer (In Case of Transfer)",
      "EXISTING_PROJECT": "Existing Project Name",
      "NEW_PROJECT": "New Project Name",
      "SIGNATURES": "Signatures",
      "APPLICANTS_SIGN": "Applicants Signature",
      "DATE": "Date",
      "PHY_ACCESS": "Physical Access Requirements (To be filled by DH/PH/PM)",
      "ZONES": "Zones",
      "PUBLIC": "Public",
      "INTERNAL": "Internal",
      "RESTRICTED": "Restricted",
      "DETAILS": "Details",
      "AUTHORIZE_SIGN": "Authorization Signatures (As Applicable)",
      "HRO": "HRO",
      "CSO": "CSO",
      "DH_PH_PM": "DH/PH/PM",
      "CISO": "CISO",
      "ACCEPT": "Accept",
      "SEND_BACK": "Send Back",
      "MESSAGE": "Message",
      "SUCCESS_MSG": "Your request has been accepted successfully",
      "BACK_MSG": "Do you really want to send it back to Supervisor",
      "YES": "Yes",
      "NO": "No"
    }

    hrdashboard: {
      "PLUGIN_CSS": "Plugin Css",
      "CUSTOM_FONTS_FOR_THIS_TEMPLATE": "Custom fonts for this template",
      "CENTRALIZED_ACCESS_CONTROL": "Centralized Access Control",
      "DASHBOARD": "Dashboard",
      "NEW_REQUEST": "New Request",
      "ACCESS_REQUESTS": "Access Requests",
      "MESSAGES": "Messages",
      "NEW_MESSAGES": "New Messages",
      "VIEW_ALL_MESSAGES": "View all Messages",
      "VIEW_ALL_ALERTS": "View all alerts",
      "BACK_TO_INIITIAN_PORTAL": "Back to Iniitian portal",
      "MY_DASHBOARD": "My Dashboard",
      "YOUR_REQUEST_IS_APPROVED_PENDING": "Your request is Approved/Pending",
      "YOUR_DETAILS": "Your Details",
      "NEW_ACCESS_REQUESTS": "New Access Requests",
      "LOCATION_CHANGE_REQUESTS": "Location Change Requests",
      "LOST_CARD_REQUESTS": "Lost Card Requests",
      "DAMAGE_REQUESTS": "Damage Requests",
      "S_NO": "S.No.",
      "EMPLOYEE_ID": "Employee Id",
      "EMPLOYEE_NAME": "Employee Name",
      "COPYRIGHT": "Iniitian.com 2017"
    }

    csoform: {
      "IR_HEADING": "IR 71 Access Request Form",
      "VERSION": "Ver 1.0",
      "GUIDELINE_MODAL": "Click Here To See Guidelines",
      "GENERAL": "General (All Fields Are Mandatory)",
      "CATEGORY": "Category",
      "ACCESS_TYPE": "Access type",
      "IR_FORM": "IR 71 Form",
      "EMP_ID": "Employee ID",
      "EMP_TYPE": "Employee Type",
      "NAME": "Name",
      "DOJ": "Date of Joining",
      "DESIGNATION": "Designation",
      "PROJECT": "Project / Function",
      "OU": "OU / Department",
      "STATUS": "Status",
      "PERMANENT": "Permanant",
      "TEMPERORY": "Temporary",
      "DOE_TEMP": "Date of Expiry of Temporary Card",
      "PROJECT_TRANSFER": "Project Transfer (In Case of Transfer)",
      "EXISTING_PROJECT": "Existing Project Name",
      "NEW_PROJECT": "New Project Name",
      "SIGNATURES": "Signatures",
      "APPLICANTS_SIGNATURES": "Applicants Signature",
      "DATE": "Date",
      "PHYSICAL_ACCESS": "Physical Access Requirements (To be filled by DH/PH/PM)",
      "ZONES": "Zones",
      "PUBLIC": "Public",
      "INTERNAL": "Internal",
      "RESTRICTED": "Restricted",
      "DETAILS": "Details",
      "ACCESS_CARD_DETAIL": "Access Card Details (To be filled by CSO)",
      "ACCESS_CARD_NUMBER": "Access Card Number",
      "ISSUED_BY": "Issued By",
      "AUTHORIZE_SIGN": "Authorization Signatures (As Applicable)",
      "HRO": "HRO",
      "CSO": "CSO",
      "DH_PH_PM": "DH/PH/PM",
      "CISO": "CISO",
      "ACCEPT": "Accept",
      "SEND_BACK": "Send Back",
      "SUCCESSFUL_ALLOT": "Access Card alloted successfully",
      "BACK_MSG": "Do you really want to send it back to Hr?",
      "MESSAGE": "Message",
      "YES": "Yes",
      "NO": "No"
    }

    csodashboard: {

    }
  }